# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llm_camera',
                'doc_host': 'https://llm_camera.github.io',
                'git_url': 'https://github.com/ninjalabo/llm_camera',
                'lib_path': 'llm_camera'},
  'syms': {'llm_camera.core': {'llm_camera.core.foo': ('core.html#foo', 'llm_camera/core.py')}}}
