# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto 0
__all__ = ['res', 'check_res', 'cleanup']

# %% ../nbs/utils.ipynb 1
import glob

# %% ../nbs/utils.ipynb 3
from PIL import Image

# %% ../nbs/utils.ipynb 5
def res(fname):
    with Image.open(fname) as img:
        w, h = img.size
        return w, h

def check_res(fname, reso):
    if reso != res(fname):
        return False
    return True

# %% ../nbs/utils.ipynb 8
def cleanup():
    for f in glob.glob("../data/*.jpg"):
        if check_res(f, (1280, 720)) == False:
            print(f, res(f))
            os.remove(f)

# %% ../nbs/utils.ipynb 13
import os

# %% ../nbs/utils.ipynb 16
import shutil
